# Trigger happy
language: objective-c
os: osx
osx_image: xcode7
xcode_project: Lambdatron.xcodeproj
xcode_scheme: Lambdatron
before_install:
  - brew update
  - brew uninstall xctool
  - brew install xctool --HEAD
